# Generated by Django 4.0.4 on 2022-04-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_country_remove_location_country_region_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['-created_at'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AddField(
            model_name='location',
            name='title',
            field=models.CharField(default='H', max_length=255),
            preserve_default=False,
        ),
    ]
