# Generated by Django 4.0.4 on 2022-04-23 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_country_options_location_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='air',
            options={'ordering': ['date'], 'verbose_name': 'Air data', 'verbose_name_plural': 'Air info'},
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['date'], 'verbose_name': 'Animal data', 'verbose_name_plural': 'Animal info'},
        ),
        migrations.AlterModelOptions(
            name='noise',
            options={'ordering': ['date'], 'verbose_name': 'Noise data', 'verbose_name_plural': 'Noise info'},
        ),
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['date'], 'verbose_name': 'Plant data', 'verbose_name_plural': 'Plant info'},
        ),
        migrations.AlterModelOptions(
            name='soil',
            options={'ordering': ['date'], 'verbose_name': 'Soil data', 'verbose_name_plural': 'Soil info'},
        ),
        migrations.AlterModelOptions(
            name='water',
            options={'ordering': ['date'], 'verbose_name': 'Water data', 'verbose_name_plural': 'Water info'},
        ),
    ]
